---
title: "ВС практикум: Домашно задание 1"
author: " "
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output:
  html_document:
    df_print: paged
    toc: false
    toc_float: true
    number_sections: false
  pdf_document: default
  word_document: default
---

<br>

При решаване на задачите може да използвате вградени функции и команди, които **не** изискват зареждане на пакет или извикване от типа `packageName::fun()`.

<br>



### Задача 1

От колекция от 100 задачи се генерират по случаен начин 20 варианта на тест, всеки с по 5 задачи, като дадена задача се среща само в един от вариантите.
От всички задачи има 20, които се класифицират като трудни. 
Разглеждаме събитието 

$\;\;$ A = { *във всеки генериран вариант има по една трудна задача* }. 

Намерете вероятността на A с помощта на симулации.



### Задача 2

Височината на холандските мъже (в сантиметри) е нормално разпределена със средно 183.8 и стандартно отклонение 7.1.
Височината на испанските мъже (в сантиметри) е нормално разпределена със средно 177.3 и стандартно отклонение 6.4.
В дадена група има само холандски и испански мъже, в съотношение 80:20. 
Разглеждаме събитията

$\;\;$ B = { *произволно избран мъж от групата е висок между 180 и 190 см* };

$\;\;$ C = { *произволно избран мъж от групата е висок над 190 см* }.

Намерете вероятностите на B и C:

- с помощта на симулации;

- като използвате вградените функции, свързани с разпределения.




